version: '3'
services:
  label-studio:
    image: heartexlabs/label-studio
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    env_file:
      - .env

    
  pre-annotations:
    build: 
      context: .
      dockerfile: ./Dockerfile
    